@startuml labReportBody-map-en
hide circle
hide stereotype
hide members
hide methods
skinparam linetype ortho
skinparam class {
BackgroundColor<<LogicalModel>> #APPLICATION
BackgroundColor<<Profile>> #TECHNOLOGY
}
legend right
| <#APPLICATION>  Logical Model |
| <#TECHNOLOGY>  Profile |
endlegend
class "Laboratory Report Body" <<LogicalModel>> [[StructureDefinition-LabReportCz.html]]

class "service-request-cz-lab" <<Profile>> [[StructureDefinition-service-request-cz-lab.html]]
class "cz-specimen-lab" <<Profile>> [[StructureDefinition-cz-specimen-lab.html]]
class "cz-observation-result-laboratory" <<Profile>> [[StructureDefinition-observation-resultlab-cz-lab.html]]
class "diagnosticReport-cz-lab" <<Profile>> [[StructureDefinition-diagnosticReport-cz-lab.html]]
class "composition-cz-lab" <<Profile>> [[StructureDefinition-composition-cz-lab.html]]

"Laboratory Report Body" <|. "service-request-cz-lab"
"Laboratory Report Body" <|. "cz-specimen-lab"
"Laboratory Report Body" <|. "cz-observation-result-laboratory"
"Laboratory Report Body" <|. "diagnosticReport-cz-lab"
"Laboratory Report Body" <|. "composition-cz-lab"

"service-request-cz-lab" -d[hidden]-> "cz-specimen-lab"
"cz-specimen-lab" -d[hidden]-> "cz-observation-result-laboratory"
"cz-observation-result-laboratory" -d[hidden]-> "diagnosticReport-cz-lab"
"diagnosticReport-cz-lab" -d[hidden]-> "composition-cz-lab"
@enduml