@startuml labReportBody-map-cs
hide circle
hide stereotype
hide members
hide methods
skinparam linetype ortho
skinparam class {
BackgroundColor<<LogicalModel>> #APPLICATION
BackgroundColor<<Profile>> #TECHNOLOGY
}
legend right
| <#APPLICATION>  Logický model |
| <#TECHNOLOGY>  Profil |
endlegend
class "Tělo laboratorní zprávy" <<LogicalModel>> [[StructureDefinition-LogLabReportCz.html]]

class "service-request-cz-lab" <<Profile>> [[StructureDefinition-service-request-cz-lab.html]]
class "cz-specimen-lab" <<Profile>> [[StructureDefinition-cz-specimen-lab.html]]
class "cz-observation-result-laboratory" <<Profile>> [[StructureDefinition-observation-resultlab-cz-lab.html]]
class "diagnosticReport-cz-lab" <<Profile>> [[StructureDefinition-diagnosticReport-cz-lab.html]]
class "composition-cz-lab" <<Profile>> [[StructureDefinition-composition-cz-lab.html]]

"Tělo laboratorní zprávy" <|. "service-request-cz-lab"
"Tělo laboratorní zprávy" <|. "cz-specimen-lab"
"Tělo laboratorní zprávy" <|. "cz-observation-result-laboratory"
"Tělo laboratorní zprávy" <|. "diagnosticReport-cz-lab"
"Tělo laboratorní zprávy" <|. "composition-cz-lab"

"service-request-cz-lab" -d[hidden]-> "cz-specimen-lab"
"cz-specimen-lab" -d[hidden]-> "cz-observation-result-laboratory"
"cz-observation-result-laboratory" -d[hidden]-> "diagnosticReport-cz-lab"
"diagnosticReport-cz-lab" -d[hidden]-> "composition-cz-lab"
@enduml